// Minimal HTTPS static file server for testing webslam on a phone over the LAN.
// getUserMedia (camera) requires a secure context, so plain http won't do off
// localhost. Serves ./web with a self-signed cert (generated by serve-phone.sh).
import https from 'node:https';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, 'web');
const PORT = process.env.PORT ? Number(process.env.PORT) : 8443;

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.mjs': 'text/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.wasm': 'application/wasm',
  '.css': 'text/css; charset=utf-8',
  '.svg': 'image/svg+xml',
};

const opts = {
  key: fs.readFileSync(path.join(__dirname, '.certs', 'key.pem')),
  cert: fs.readFileSync(path.join(__dirname, '.certs', 'cert.pem')),
};

https
  .createServer(opts, (req, res) => {
    let urlPath = decodeURIComponent(req.url.split('?')[0]);
    if (urlPath === '/') urlPath = '/index.html';
    // Prevent path traversal.
    const filePath = path.join(ROOT, path.normalize(urlPath));
    if (!filePath.startsWith(ROOT)) { res.writeHead(403); res.end('forbidden'); return; }
    fs.readFile(filePath, (err, data) => {
      if (err) { res.writeHead(404); res.end('not found'); return; }
      const ext = path.extname(filePath).toLowerCase();
      res.writeHead(200, {
        'Content-Type': MIME[ext] || 'application/octet-stream',
        // No caching — so a phone always picks up the latest build on reload.
        'Cache-Control': 'no-store, no-cache, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0',
      });
      res.end(data);
    });
  })
  .listen(PORT, '0.0.0.0', () => {
    console.log(`webslam serving https on 0.0.0.0:${PORT}`);
  });
